import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { writeFileSync, existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { hashPassword } from './password.mjs';
if (existsSync('.env.docker')) throw new Error('.env.docker already exists. Edit it directly; this command will not overwrite it.');
const rl = createInterface({input:stdin,output:stdout});
const address = (process.argv.includes('--defaults') ? '' : await rl.question('访问地址（默认 http://127.0.0.1:3000）：')).trim() || 'http://127.0.0.1:3000';
const origin = new URL(address);
if (!['http:','https:'].includes(origin.protocol) || origin.origin !== address) throw new Error('请输入完整访问源，不含路径或末尾斜杠');
const username = (process.argv.includes('--defaults') ? '' : await rl.question('管理员账号（默认 admin）：')).trim() || 'admin';
rl.close();
if (!/^[a-zA-Z0-9_.-]{3,40}$/.test(username)) throw new Error('管理员账号需为 3–40 位字母、数字、下划线或连字符');
const password = randomBytes(24).toString('base64url');
const passwordHash = await hashPassword(password);
const file = `APP_ORIGIN=${address}\nBIND_ADDRESS=127.0.0.1\nPORT=3000\nADMIN_USERNAME=${username}\nADMIN_PASSWORD_HASH=${passwordHash}\nOTP_SECRET=${randomBytes(32).toString('hex')}\nALIYUN_ACCESS_KEY_ID=\nALIYUN_ACCESS_KEY_SECRET=\nSMS_SIGN_NAME=\nSMS_TEMPLATE_CODE=\nAI_API_KEY=\nAI_MODEL=\n`;
writeFileSync('.env.docker',file,{mode:0o600,flag:'wx'});
console.log('\n已生成 .env.docker。请保存下面的初始密码（文件中仅存储密码散列）：\n管理员：'+username+'\n初始密码：'+password+'\n');
